<a href="https://colab.research.google.com/github/IlliaKindratenko/Machine-learning/blob/main/%D0%9B_%D0%A0_1_%D0%9A%D1%96%D0%BD%D0%B4%D1%80%D0%B0%D1%82%D0%B5%D0%BD%D0%BA%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

11 Варіант

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy

In [ ]:
import pandas as pd

start = 3
step = 5
size = 10

# Використання функції pd.Series для створення одновимірного масиву
sequence = pd.Series([start + step * i for i in range(size)])

print(sequence)


0     3
1     8
2    13
3    18
4    23
5    28
6    33
7    38
8    43
9    48
dtype: int64


In [ ]:
import numpy as np

# Початкове число
start = 1

# Створення порожньої матриці 3x3
matrix = np.zeros((3, 3), dtype=int)

# Заповнення матриці добутками кожного числа та його попереднього
current_value = start
for i in range(3):
    for j in range(3):
        if current_value == 1:
            matrix[i, j] = 1
        else:
            matrix[i, j] = current_value * (current_value - 1)
        current_value += 1

print(matrix)


[[ 1  2  6]
 [12 20 30]
 [42 56 72]]


In [ ]:
import numpy as np

# Створення матриці 3x3 з випадковими натуральними числами від 1 до 2
matrix = np.random.randint(1, 3, size=(3, 3))

# Обчислення середнього арифметичного елементів матриці
mean_value = np.mean(matrix)

print("Матриця:")
print(matrix)
print("\nСереднє арифметичне елементів:", mean_value)


Матриця:
[[2 2 1]
 [2 1 2]
 [1 1 2]]

Середнє арифметичне елементів: 1.5555555555555556


In [ ]:
import numpy as np

# Створення матриці 4x4 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(4, 4)

# Знаходження кількості елементів, що більше 0.5
count_greater_than_0_5 = np.sum(matrix > 0.5)

print("Матриця:")
print(matrix)
print("\nКількість елементів більше 0.5:", count_greater_than_0_5)


Матриця:
[[0.15222797 0.88828083 0.80554233 0.48191789]
 [0.51281008 0.73648968 0.14236477 0.18371005]
 [0.07799427 0.76748696 0.24682642 0.75034424]
 [0.08391323 0.33807745 0.74421146 0.56074855]]

Кількість елементів більше 0.5: 8


In [ ]:
import numpy as np

# Створення двох масивів розміром 7 з випадковими цілими числами від -15 до 15
array1 = np.random.randint(-15, 16, size=7)
array2 = np.random.randint(-15, 16, size=7)

# Поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Масив 1:")
print(array1)

print("\nМасив 2:")
print(array2)

print("\nПоелементне додавання:")
print(addition)

print("\nПоелементне віднімання:")
print(subtraction)

print("\nПоелементне множення:")
print(multiplication)


Масив 1:
[  7 -12  -6   3  -4 -15   2]

Масив 2:
[  1   0   9 -15  10  11   7]

Поелементне додавання:
[  8 -12   3 -12   6  -4   9]

Поелементне віднімання:
[  6 -12 -15  18 -14 -26  -5]

Поелементне множення:
[   7    0  -54  -45  -40 -165   14]


In [ ]:
import numpy as np

# Створення двох матриць 4x4 з довільними цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Знаходження добутку двох матриць
product_matrix = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nДобуток матриць:")
print(product_matrix)


Матриця 1:
[[ 9  2  2  5]
 [ 7 10  9  1]
 [ 5  4  1  9]
 [ 6  5  2  9]]

Матриця 2:
[[ 8  8  2  5]
 [ 4  5  8  4]
 [ 1 10  8  5]
 [ 2  5  1  4]]

Добуток матриць:
[[ 92 127  55  83]
 [107 201 167 124]
 [ 75 115  59  82]
 [ 88 138  77  96]]


In [ ]:
import numpy as np

# Створення матриці розміром 4x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 2))

# Створення матриці розміром 2x5 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 5))

# Перемноження двох матриць
product_matrix = np.dot(matrix1, matrix2)

print("Матриця 1 (4x2):")
print(matrix1)

print("\nМатриця 2 (2x5):")
print(matrix2)

print("\nДобуток матриць (4x5):")
print(product_matrix)


Матриця 1 (4x2):
[[ 8  6]
 [ 2  5]
 [ 1 10]
 [ 6  2]]

Матриця 2 (2x5):
[[ 1  9  8  5  2]
 [ 8  8  6  7 10]]

Добуток матриць (4x5):
[[ 56 120 100  82  76]
 [ 42  58  46  45  54]
 [ 81  89  68  75 102]
 [ 22  70  60  44  32]]


In [ ]:
import numpy as np

# Створення матриці розміром 2x2 з випадковими цілими числами від 1 до 12
matrix = np.random.randint(1, 13, size=(2, 2))

# Обчислення оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

print("Матриця 2x2:")
print(matrix)

print("\nОбернена матриця:")
print(inverse_matrix)


Матриця 2x2:
[[11  9]
 [ 3  7]]

Обернена матриця:
[[ 0.14 -0.18]
 [-0.06  0.22]]


In [ ]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(3, 3)

# Транспонування матриці
transposed_matrix = matrix.T

print("Матриця 3x3:")
print(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця 3x3:
[[0.92997571 0.79894601 0.65978839]
 [0.46209662 0.31747202 0.34870381]
 [0.27740464 0.4466052  0.34299906]]

Транспонована матриця:
[[0.92997571 0.46209662 0.27740464]
 [0.79894601 0.31747202 0.4466052 ]
 [0.65978839 0.34870381 0.34299906]]


In [ ]:
import numpy as np

# Створення матриці розміром 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створення вектора розміром 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4, 1)

# Знаходження добутку матриці та вектора
product = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця 3x4:
[[0.20675796 0.80029583 0.27182078 0.44502091]
 [0.39010801 0.52792515 0.17746529 0.01915788]
 [0.36319784 0.39582713 0.53406665 0.96363964]]

Вектор 4x1:
[[0.76415375]
 [0.06319878]
 [0.46411183]
 [0.08953245]]

Добуток матриці на вектор:
[[0.37457164]
 [0.41554572]
 [0.63669845]]


In [ ]:
import numpy as np

# Створення матриці розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора розміром 3 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=3)

# Знаходження добутку матриці на вектор
product = np.dot(matrix, vector)

print("Матриця 2x3:")
print(matrix)

print("\nВектор 3:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця 2x3:
[[0.30115471 0.33027862 0.91878437]
 [0.75929196 0.16099592 0.79488947]]

Вектор 3:
[4 5 8]

Добуток матриці на вектор:
[10.20628691 10.2012632 ]


In [ ]:
import numpy as np

# Створення двох матриць розміром 4x4 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Обчислення різниці між матрицями
difference = matrix1 - matrix2

print("Матриця 1 (4x4):")
print(matrix1)

print("\nМатриця 2 (4x4):")
print(matrix2)

print("\nРізниця матриць:")
print(difference)


Матриця 1 (4x4):
[[ 1  2  1  7]
 [ 8  7  5  6]
 [ 8  8  1  2]
 [ 6  5 10  2]]

Матриця 2 (4x4):
[[ 8  3  8  9]
 [ 1  6  8  1]
 [ 3  4  2  3]
 [ 1  9  5 10]]

Різниця матриць:
[[-7 -1 -7 -2]
 [ 7  1 -3  5]
 [ 5  4 -1 -1]
 [ 5 -4  5 -8]]


In [ ]:
import numpy as np

# Створення двох матриць розміром 3x3 з випадковими дійсними числами від -1 до 1
matrix1 = np.random.uniform(-1, 1, size=(3, 3))
matrix2 = np.random.uniform(-1, 1, size=(3, 3))

# Обчислення суми всіх елементів матриць
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

print("Матриця 1 (3x3):")
print(matrix1)

print("\nМатриця 2 (3x3):")
print(matrix2)

print("\nСума всіх елементів Матриці 1:", sum_matrix1)
print("Сума всіх елементів Матриці 2:", sum_matrix2)


Матриця 1 (3x3):
[[ 0.64270502 -0.74549303  0.43027284]
 [ 0.45010125  0.78711073 -0.5482072 ]
 [ 0.0737424  -0.8120057  -0.08275013]]

Матриця 2 (3x3):
[[ 0.01489558  0.32003768 -0.3530975 ]
 [ 0.61703127  0.6550361  -0.56601669]
 [ 0.03788649  0.15403555 -0.13460209]]

Сума всіх елементів Матриці 1: 0.19547618612949424
Сума всіх елементів Матриці 2: 0.745206389247137


In [ ]:
import numpy as np

# Створення матриці розміром 3x3 з випадковими дійсними числами від -3 до 3
matrix = np.random.uniform(-3, 3, size=(3, 3))

# Знаходження кількості парних елементів матриці
#Перетворюємо матрицю на цілі числа і потім перевіряємо парність
integer_matrix = np.round(matrix).astype(int)
even_elements_count = np.sum(integer_matrix % 2 == 0)

print("Матриця 3x3:")
print(matrix)

print("\nКількість парних елементів матриці:", even_elements_count)


Матриця 3x3:
[[-0.08408763 -2.77143571  0.23179578]
 [ 1.49496543  0.01442561  0.13150306]
 [-1.0003699  -2.22362307 -2.95668172]]

Кількість парних елементів матриці: 5


In [ ]:
import numpy as np
from scipy.stats import gmean

# Створення матриці розміром 5x5 з випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))

# Функція для обчислення середнього геометричного з урахуванням від'ємних чисел
def geometric_mean_with_non_positive(x):
    x_positive = x[x > 0]
    return gmean(x_positive) if len(x_positive) > 0 else np.nan

# Обчислення середнього геометричного значення кожного рядка
geo_mean_vector = np.array([geometric_mean_with_non_positive(row) for row in matrix])

print("Матриця 5x5:")
print(matrix)

print("\nВектор середніх геометричних значень рядків:")
print(geo_mean_vector)


Матриця 5x5:
[[-0.41407118  0.3496819   0.08077432 -0.35812722 -0.06468533]
 [ 0.48860344  0.09658285  0.26824521  0.14216546 -0.06288859]
 [-0.47459955 -0.14540051 -0.0502079  -0.11047972  0.20295275]
 [-0.3961755   0.11021493  0.11071154  0.27375461  0.38994791]
 [ 0.37450428 -0.22422514  0.06837535 -0.26937179 -0.04633921]]

Вектор середніх геометричних значень рядків:
[0.16806344 0.20596606 0.20295275 0.1899767  0.16002144]


Висновок: було проведено різні маніпуляції з матрицями і векторами, також згадали та ознайомилися з функціями бібліотекою numpy.